server:
  port: 8080

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    timeout: 1000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0

custom:
  redis:
    default-expire-time: 3600
debug: true
